services:
  universal-tts:
    build: .
    ports:
      - "7862:7862"
    volumes:
      - ./models:/app/models
      - ./finetune_models:/app/finetune_models
      # Mount your audio inputs here to access them in the container
      - ./audio_data:/app/audio_data
    # Enable GPU support if you have an NVIDIA GPU and nvidia-container-toolkit installed
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
